/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as JobCategoriesRouteImport } from './routes/job-categories'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VacanciesIndexRouteImport } from './routes/vacancies.index'
import { Route as VacanciesSlugRouteImport } from './routes/vacancies.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const JobCategoriesRoute = JobCategoriesRouteImport.update({
  id: '/job-categories',
  path: '/job-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesIndexRoute = VacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesSlugRoute = VacanciesSlugRouteImport.update({
  id: '/vacancies/$slug',
  path: '/vacancies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/credentials': typeof CredentialsRoute
  '/employers': typeof EmployersRoute
  '/job-categories': typeof JobCategoriesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vacancies/$slug': typeof VacanciesSlugRoute
  '/vacancies/': typeof VacanciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/credentials': typeof CredentialsRoute
  '/employers': typeof EmployersRoute
  '/job-categories': typeof JobCategoriesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vacancies/$slug': typeof VacanciesSlugRoute
  '/vacancies': typeof VacanciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/credentials': typeof CredentialsRoute
  '/employers': typeof EmployersRoute
  '/job-categories': typeof JobCategoriesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vacancies/$slug': typeof VacanciesSlugRoute
  '/vacancies/': typeof VacanciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/candidates'
    | '/contact'
    | '/countries'
    | '/credentials'
    | '/employers'
    | '/job-categories'
    | '/privacy'
    | '/terms'
    | '/vacancies/$slug'
    | '/vacancies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/candidates'
    | '/contact'
    | '/countries'
    | '/credentials'
    | '/employers'
    | '/job-categories'
    | '/privacy'
    | '/terms'
    | '/vacancies/$slug'
    | '/vacancies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/candidates'
    | '/contact'
    | '/countries'
    | '/credentials'
    | '/employers'
    | '/job-categories'
    | '/privacy'
    | '/terms'
    | '/vacancies/$slug'
    | '/vacancies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CandidatesRoute: typeof CandidatesRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRoute
  CredentialsRoute: typeof CredentialsRoute
  EmployersRoute: typeof EmployersRoute
  JobCategoriesRoute: typeof JobCategoriesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VacanciesSlugRoute: typeof VacanciesSlugRoute
  VacanciesIndexRoute: typeof VacanciesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-categories': {
      id: '/job-categories'
      path: '/job-categories'
      fullPath: '/job-categories'
      preLoaderRoute: typeof JobCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies/': {
      id: '/vacancies/'
      path: '/vacancies'
      fullPath: '/vacancies/'
      preLoaderRoute: typeof VacanciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies/$slug': {
      id: '/vacancies/$slug'
      path: '/vacancies/$slug'
      fullPath: '/vacancies/$slug'
      preLoaderRoute: typeof VacanciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CandidatesRoute: CandidatesRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRoute,
  CredentialsRoute: CredentialsRoute,
  EmployersRoute: EmployersRoute,
  JobCategoriesRoute: JobCategoriesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VacanciesSlugRoute: VacanciesSlugRoute,
  VacanciesIndexRoute: VacanciesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
